baseURL: "https://www.egger.cloud"
title: 'Blog'
paginate: 3
theme: papermod
DefaultContentLanguage: "fr"
enableInlineShortcodes: true

minify:
    disableXML: true


params:
    twitter: 'franc01s'
    github: 'franc01s'
    avatar: 'francois@egger.cloud'
    name: 'François'
    bio: 'Let''s talk about subjects I found cool at this moment'
    rss: true

menu:
    main:
            
        - identifier: "search"
          name: "Search"
          url: "search/"
          weight: 10
        
        - identifier: "about"
          name: "About"
          url: "/about/"
          weight: 10

        - identifier: "contact"
          name: "Contact"
          url: "/contact/"
          weight: 10

markup:
    goldmark:
        renderer:
            unsafe: true

privacy:
    twitter:
        disabled: false
        enableDNT: true
        simple: true
    vimeo:
        disabled: true
        simple: true
    instagram:
        disabled: true
        simple: true
    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
